name: Prod Deploy Serverless
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Download Artifact
        run: |
          # Fetch the latest artifact URL from a previous workflow run
          ARTIFACT_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=push&status=success" | \
                        jq -r '.workflow_runs[0].artifacts_url')

          # Download the artifact
          curl -s -L -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              "$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                "$ARTIFACT_URL" | \
                jq -r '.artifacts[0].archive_download_url')?$(date +%s)" \
              --output service-sid.txt

      - name: Setup Twilio CLI and promote environment
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
          TWILIO_FUNCTIONS_SERVICE_SID: ${{ secrets.TWILIO_FUNCTIONS_SERVICE_SID }}
        run: TWILIO_FUNCTIONS_SERVICE_SID=$(cat service-sid.txt) && npm install -g twilio-cli && twilio plugins:install @twilio-labs/plugin-serverless && npm run promote
